[versions]
paperweight = "2.0.0-beta.19"
kotlin = "2.3.0"
ktoml = "0.7.1"
floodgate = "2.2.4-SNAPSHOT"
lamp = "4.0.0-rc.19"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }

[libraries]
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
ktoml-file = { module = "com.akuleshov7:ktoml-file", version.ref = "ktoml" }
floodgate-api = { module = "org.geysermc.floodgate:api", version.ref = "floodgate" }
lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-paper = { module = "io.github.revxrsal:lamp.bukkit", version.ref = "lamp" }
