package io.github.bradenk04.claims.domain

enum class ClaimPermission {
    PICKUP_ITEMS,
    DROP_ITEMS,
    ENTER_REGION,
    ADD_TO_CLAIM,
    BREAK_BLOCKS,
    PLACE_BLOCKS,
    CLICK_BUTTONS,
    MODIFY_ARMOR_STANDS,
    USE_LEVERS,
    USE_PRESSURE_PLATES,
    OPEN_DOORS,
    OPEN_TRAPDOORS,
    OPEN_FENCE_GATES,
    TRIGGER_TRIPWIRE,
    RING_BELL,
    GENERIC_INTERACT
}